new feature:RequestHandler.reply's parameter data can be a function
lomsa-dev/http-mock-adapter pull request #123
Opened 2021-08-28 13:07 UTC by wangdengwu

# Pull Request Template

## Your checklist for this pull request

Please review the [guidelines for contributing](https://github.com/lomsa-dev/http-mock-adapter/blob/develop/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a `feature`/`bugfix` branch** (right side). Don't request your `main` or `develop`!
- [x] Make sure you are making a pull request against the **`develop` branch** (left side). Also, you should start *your branch* off *our `develop`*.
- [x] Make sure that you add reviewers, assignees, labels, projects, milestones and linkes issues to the pull request as you see fit.
- [x] Check the commit's or even all commits' message styles to match our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

**Tip**: Delete everything but the following section that contains the description of the pull request.

---

## Description
For mock http request, not just for unit test. so RequestHandler.reply's parameter data should be function.
so when the real RequestOptions pass in ,the return data can be code with logic.

Please describe your pull request.

Thank you!

2021-09-17 17:24 UTC, theiskaa approved these changes
Everything is ok, but we should make some little changes in code to make it better.

2021-09-17 17:24 UTC, theiskaa commented on lib/src/extensions/matches_request.dart
> +    if (expected is MockDataCallback) {
We should replace 
```dart
if (expected is MockDataCallback) return true;
```

2021-09-17 17:30 UTC, LukaGiorgadze commented
Thanks @wangdengwu for contributing and helping **http-mock-adapter**.
Looks good, but it seems some CI/CD tools is failing, including linter. Please fix that and we will re-review then.

@theiskaa Btw, have you a chance to test it on your device/simulator?

2021-09-17 17:48 UTC, theiskaa requested changes
I put some suggestions to make code look better.

2021-09-17 17:48 UTC, theiskaa commented on lib/src/extensions/matches_request.dart
> +    }
Sorry, I forgot to mention some little changes to make code better look.

Please change to:
```dart
//  If data is MockDataCallback do not need to match.
if (expected is MockDataCallback) return true
```

2021-09-17 17:48 UTC, theiskaa commented on test/extensions/matches_request_test.dart
> +          'b': 'b',
Remove unneeded comma here. So, the variable should be like this:
```dart
const actual = {'a': 'a', 'b': 'b'}
```

2021-09-17 17:48 UTC, theiskaa commented on test/mixins/recording_test.dart
> +        'name': 'mock',
Remove unneeded comma here. So, the variable should be like this:
```dart
  var data = {'id': 1,  'name': 'mock'}
```

2021-09-17 17:48 UTC, theiskaa commented on test/handlers/request_handler_test.dart
> +      };
I don't like this frequency.

2021-09-17 17:48 UTC, theiskaa commented on test/handlers/request_handler_test.dart
> +        inputData,
Remove unneeded comma here. So, the request should be like this:
```dart
requestHandler.reply(statusCode, inputData);
```

2021-09-17 17:50 UTC, theiskaa commented
> Thanks @wangdengwu for contributing and helping **http-mock-adapter**.
> Looks good, but it seems some CI/CD tools is failing, including linter. Please fix that and we will re-review then.
> 
> @theiskaa Btw, have you a chance to test it on your device/simulator?

I'll do it now ... Sorry, I was confused, my fault :/

2021-09-24 05:49 UTC, wangdengwu commented
got it 
i will clean the code then pull request again
thanks for review 🙂

2021-09-24 12:59 UTC, theiskaa approved these changes
Looks good. 

@GiorgiBeriashvili could you look main idea of PR and tell your thoughts?
Code is ok, just we need review for main idea.

@wangdengwu Thanks for PR 🙌🏻

2021-09-24 22:20 UTC, GiorgiBeriashvili approved these changes
Thank you for the PR!

I analyzed the code, I approve of the intention and think that it is a helpful feature. Though, I am unsure if `if (expected is MockDataCallback) return true;` is the right way to handle the matching since it will disregard any real matching logic and accept any `expected` argument that has a `MockDataCallback` method definition, but it can be handled later if problems arise.

Thus, I approve.

2021-09-24 22:23 UTC, GiorgiBeriashvili commented
@theiskaa What do you think about hard-coded `return true` expression I mentioned [here](https://github.com/lomsa-dev/http-mock-adapter/pull/123#pullrequestreview-763509960)?

Do you have any suggestions/solutions or should we merge? I will leave it up to you. ^_^

2021-09-25 09:25 UTC, theiskaa commented
Thank you @GiorgiBeriashvili. I don't think it would make any problem. So, we should merge for now, as you mentioned it can be handled later if problems arise.

2021-09-25 09:25 UTC, merged