Add non-sequential responding and improve result of fetching
lomsa-dev/http-mock-adapter pull request #22
Opened 2020-11-17 21:42 UTC by GiorgiBeriashvili

Resolves #5

2020-11-19 16:26 UTC, nataliehippe commented
Do we leave it as it is yet?

2020-11-20 08:13 UTC, LukaGiorgadze requested changes

2020-11-20 08:13 UTC, LukaGiorgadze commented on lib/src/interceptors/dio_interceptor.dart
> +    headers.set(Headers.contentTypeHeader, [Headers.jsonContentType]);
I would prefer to remove extra line breaks there, like:

```
final responseBody = history.responseBody(options);
responseBody.headers = responseBody.headers ?? {};

final headers = Headers.fromMap(responseBody.headers ?? {});
headers.set(Headers.contentTypeHeader, [Headers.jsonContentType]);
```

2020-11-20 08:13 UTC, LukaGiorgadze commented on test/http_mock_adapter_test.dart
> +  final statusCode = 200;
use `const` instead of `final`

2020-11-20 14:35 UTC, nataliehippe reviewed
Everything seems good. Waiting for Dato's review.

2020-11-20 16:07 UTC, campfire5 approved these changes

2020-11-20 16:08 UTC, merged